package tcap

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"github.com/fkgi/gsmap"
)

/*
TcAbort

	Abort ::= SEQUENCE {
		dtid   DestTransactionID,
		reason CHOICE {
			p-abortCause P-AbortCause,
			u-abortCause DialoguePortion } OPTIONAL }

The u-abortCause may be generated by the component sublayer in which case it is an ABRT APDU,
or by the TC-User in which case it could be either an ABRT APDU or data in some user-defined abstract syntax.
*/
type TcAbort struct {
	dtid   uint32
	pCause Cause
	uCause Dialogue
}

func (m TcAbort) String() string {
	buf := new(strings.Builder)
	fmt.Fprintf(buf, "TC-ABORT (dtid=%x)", m.dtid)
	if m.uCause != nil {
		fmt.Fprint(buf, "\n | u-abortCause:", m.uCause)
	} else {
		fmt.Fprint(buf, "\n | ", m.pCause)
	}
	return buf.String()
}

func (m TcAbort) Error() string {
	if m.uCause != nil {
		return "Aborted by peer with u-abortCause"
	}
	if m.pCause < 0x10 {
		return fmt.Sprint("Aborted by peer with ", m.pCause)
	}
	return fmt.Sprint("Internal error with ", m.pCause)
}

/*
Cause

	P-AbortCause ::= [APPLICATION 10] IMPLICIT INTEGER {
		unrecognizedMessageType          (0),
		unrecognizedTransactionID        (1),
		badlyFormattedTransactionPortion (2),
		incorrectTransactionPortion      (3),
		resourceLimitation               (4) }
*/
type Cause byte

const (
	TcUnrecognizedMessageType          Cause = 0x00
	TcUnrecognizedTransactionID        Cause = 0x01
	TcBadlyFormattedTransactionPortion Cause = 0x02
	TcIncorrectTransactionPortion      Cause = 0x03
	TcResourceLimitation               Cause = 0x04

	TcTimeout       Cause = 0x10
	TcNoDestination Cause = 0x11
	TcDiscard       Cause = 0x12
)

func (c Cause) String() string {
	switch c {
	case TcUnrecognizedMessageType:
		return "p-abortCause: unrecognizedMessageType"
	case TcUnrecognizedTransactionID:
		return "p-abortCause: unrecognizedTransactionID"
	case TcBadlyFormattedTransactionPortion:
		return "p-abortCause: badlyFormattedTransactionPortion"
	case TcIncorrectTransactionPortion:
		return "p-abortCause: incorrectTransactionPortion"
	case TcResourceLimitation:
		return "p-abortCause: resourceLimitation"
	case TcTimeout:
		return "responseTimeout(internal)"
	case TcNoDestination:
		return "noDestinationFound(internal)"
	case TcDiscard:
		return "discard(internal)"
	default:
		return fmt.Sprintf("p-abortCause: unknown(%x)", byte(c))
	}
}

func (m *TcAbort) marshalTc() []byte {
	buf := new(bytes.Buffer)

	// dtid, application(40) + primitive(00) + 9(09)
	buf.Write(marshalTid(0x49, m.dtid))

	// p-AbortCause, application(40) + primitive(00) + 10(0a)
	if m.uCause == nil {
		gsmap.WriteTLV(buf, 0x4a, []byte{byte(m.pCause)})
	}

	// u-abortCause, application(40) + constructed(20) + 11(0b)
	if m.uCause != nil {
		gsmap.WriteTLV(buf, 0x6b, marshalDialogue(m.uCause))
	}

	// TcEnd, application(40) + constructed(20) + 4(07)
	return gsmap.WriteTLV(new(bytes.Buffer), 0x67, buf.Bytes())
}

func unmarshalTcAbort(data []byte) (m *TcAbort, e error) {
	m = &TcAbort{}
	buf := bytes.NewBuffer(data)

	// dtid, application(40) + primitive(00) + 9(09)
	if m.dtid, e = unmarshalTid(buf, 0x49); e != nil {
		return
	}

	t, v, e := gsmap.ReadTLV(buf, 0x00)
	if e == io.EOF {
		e = nil
	} else if e != nil {
		return
	}
	switch t {
	case 0x6b: // u-abortCause, application(40) + constructed(20) + 11(0b)
		m.uCause, e = unmarshalDialogue(v)
	case 0x4a: // p-AbortCause, application(40) + primitive(00) + 10(0a)
		if len(v) != 1 || v[0] > 4 {
			e = gsmap.UnexpectedTLV("invalid parameter value")
		} else {
			m.pCause = Cause(v[0])
		}
	default:
		e = gsmap.UnexpectedTag([]byte{0x6b, 0x4a}, t)
	}
	return
}

func (m TcAbort) Components() []gsmap.Component {
	return nil
}

func (m TcAbort) Cause() (Cause, Dialogue) {
	return m.pCause, m.uCause
}
